[nltk_data] Downloading package punkt to /home/zyna/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
E
======================================================================
ERROR: test_01_calc_sims (hw07_knn.test_knn.ClassificationTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File .../tmp_repositories/abgabe/hw07_knn/WinxClub/src/hw07_knn/test_knn.py", line 33, in test_01_calc_sims
    sorted_dist = sorted(dist)
TypeError: 'NoneType' object is not iterable

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)
[nltk_data] Downloading package punkt to /home/zyna/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
F
======================================================================
FAIL: test_02_order_near_to_far (hw07_knn.test_knn.ClassificationTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File .../tmp_repositories/abgabe/hw07_knn/WinxClub/src/hw07_knn/test_knn.py", line 38, in test_02_order_near_to_far
    self.assertEqual([(0.7,"a"),(0.5,"b"),(0.2,"c")],classifier.order_nearest_to_farthest(test_distances))
AssertionError: [(0.7, 'a'), (0.5, 'b'), (0.2, 'c')] != None

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (failures=1)
[nltk_data] Downloading package punkt to /home/zyna/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
E
======================================================================
ERROR: test_03_labels_k_closest (hw07_knn.test_knn.ClassificationTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File .../tmp_repositories/abgabe/hw07_knn/WinxClub/src/hw07_knn/test_knn.py", line 42, in test_03_labels_k_closest
    self.assertEqual(k_nearest_labels[0],'alt.atheism')
TypeError: 'NoneType' object is not subscriptable

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)
[nltk_data] Downloading package punkt to /home/zyna/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
F
======================================================================
FAIL: test_04_choose_neighbor (hw07_knn.test_knn.ClassificationTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File .../tmp_repositories/abgabe/hw07_knn/WinxClub/src/hw07_knn/test_knn.py", line 46, in test_04_choose_neighbor
    self.assertEqual(winner,'rec.sport.hockey')
AssertionError: None != 'rec.sport.hockey'

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (failures=1)
[nltk_data] Downloading package punkt to /home/zyna/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
F
======================================================================
FAIL: test_05_classify (hw07_knn.test_knn.ClassificationTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File .../tmp_repositories/abgabe/hw07_knn/WinxClub/src/hw07_knn/test_knn.py", line 52, in test_05_classify
    self.assertEqual(classifier.classify(test_file),'alt.atheism')
AssertionError: None != 'alt.atheism'

----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (failures=1)
[nltk_data] Downloading package punkt to /home/zyna/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
F
======================================================================
FAIL: test_06_accuracy (hw07_knn.test_knn.ClassificationTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File .../tmp_repositories/abgabe/hw07_knn/WinxClub/src/hw07_knn/test_knn.py", line 63, in test_06_accuracy
    self.assertEqual(accuracy,75)
AssertionError: None != 75

----------------------------------------------------------------------
Ran 1 test in 0.011s

FAILED (failures=1)
